// <auto-generated />
using LocalBusiness.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LocalBusiness.Migrations
{
    [DbContext(typeof(LocalBusinessContext))]
    [Migration("20210611210709_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("LocalBusiness.Models.Business", b =>
                {
                    b.Property<int>("BusinessId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("BusinessId");

                    b.ToTable("Businesses");

                    b.HasData(
                        new
                        {
                            BusinessId = 1,
                            Location = "4207 University Way NE",
                            Name = "Pho Than Brothers"
                        },
                        new
                        {
                            BusinessId = 2,
                            Location = "223 North 36th Street Seattle",
                            Name = "Outsider Comics and Geek Boutique"
                        },
                        new
                        {
                            BusinessId = 3,
                            Location = "346 15th Avenue East, Seattle",
                            Name = "Agora"
                        },
                        new
                        {
                            BusinessId = 4,
                            Location = "1101 East Union Street, Seattle",
                            Name = "Likelihood"
                        },
                        new
                        {
                            BusinessId = 5,
                            Location = "310 Occidental Avenue South, Seattle",
                            Name = "Clementines"
                        },
                        new
                        {
                            BusinessId = 6,
                            Location = "Online",
                            Name = "Thea Candle Co"
                        },
                        new
                        {
                            BusinessId = 7,
                            Location = "1430 Western Avenue, Seattle",
                            Name = "Ugly Baby Shop"
                        },
                        new
                        {
                            BusinessId = 8,
                            Location = "1100 E Pike Street, Seattle",
                            Name = "35th North"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
